server:
  port: 80

#配置数据源、配置时间响应
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    #时间响应格式
    date-format: yyyy-MM-dd HH:mm:ss
    #设置时区
    time-zone: GMT+8
  devtools:
    restart:
      #热部署开启设置、
      enabled: true
      #配置重启目录
      additional-paths: src/main/java

#配置mybaits
mybatis:
  #配置mapper的扫描、找到所有类路径下mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  #搜索指定的包名
  type-aliases-package: com.sample.entity,com.common.bean,com.sample.entity.ext
  configuration:
    #配置启动打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis 驼峰命名
#    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: false

#springboot启动打印日志
logging:
  level: 
#日志级别 trace debug info warm error
    root: info
#  日志输出文件名
#  file: sample-Logs.log

#配置PageHelper 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql 
